version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb+srv://mdmehedihasanrifat2407nsu:zillow@cluster0.dopsh.mongodb.net/vehicle_allocation?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mdmehedihasanrifat2407nsu
      - MONGO_INITDB_ROOT_PASSWORD=zillow
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: